### ISSUE TITLE
md2hlp can't be launch from everywhere : md2help.cfg is not found

### ISSUE THREAD

**Issue by jedeoric** [assinie/md2hlp#1]
md2help.cfg is required to launch md2hlp.py. Anyway, when we put md2hlp in PATH variable, it can't found md2hlp.cfg.

md2help.py should detect where source code is in order to find md2hlp.cfg (or at least a variable environnement)

**Comment by assinie** [comment]
Can't reproduce the bug.
md2hlp.py search it's configuration file in the current directory.
You can also use a specific configuration file with the **-c** or **--config** option on the command line:
```
md2hlp.py --config /pat/to/md2hlp.cfg --file help.md

**Comment by assinie** [comment]
Added new environment variable: **MD2HLP_PATH**.
If set, md2hlp.py uses it as the path to search for configuration file. It is overridden by the -c invocation option.

**Comment by jedeoric** [comment]
ok thanks :)
